version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres-nest
    environment:
      POSTGRES_USER: campusito
      POSTGRES_PASSWORD: campusito
      POSTGRES_DB: campusito
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: